//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uvelir
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public string OrderList { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> OrderDeliveryDate { get; set; }
        public string OrderUser { get; set; }
        public Nullable<int> OrderCodeToReceive { get; set; }
        public Nullable<int> OrderPickupPoint { get; set; }
        public string OrderStatus { get; set; }
    
        public virtual OrderStatus OrderStatus1 { get; set; }
        public virtual PickupPoint PickupPoint { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
